version: "3.7"

services:
  postgres:
    container_name: runbot_db
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - ${DOCKER_POSTGRES_PORT}
    volumes:
      - postgres:/data/postgres
    environment:
      - POSTGRES_DB=$DATABASE_DB
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    networks:
      - running

  server:
    container_name: runbot_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/go/src/telegramStravaBot
    depends_on:
      - postgres
    command: ["./wait-for-postgres.sh"]
    networks:
      - running
    ports:
      - ${DOCKER_SERVER_PORT}
  adminer:
    image: adminer:4
    container_name: "runbot_adminer"
    restart: always
    ports:
      - ${DOCKER_ADMINER_PORT:-8669}:8080
    networks:
      - running
networks:
  running:
    driver: "bridge"
volumes:
  postgres:
  pgadmin:
