version: "3.7"

services:
  postgres:
    container_name: runbot_db
    image: postgres:14-alpine3.14
    restart: always
    env_file:
      - .env
    ports:
      - ${DOCKER_POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/repositories
    environment:
      - POSTGRES_DB=$DATABASE_DB
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DATABASE_USER -d $DATABASE_DB" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - running
      - default

  redis:
    container_name: runbot_redis
    image: redis:6-alpine3.14
    restart: unless-stopped
    ports:
      - ${DOCKER_REDIS_PORT:-6379}:6379
    networks:
      - running
      - default

  server:
    container_name: runbot_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/go/src/telegramStravaBot
    depends_on:
      - postgres
    networks:
      - running
    ports:
      - ${DOCKER_SERVER_PORT}
networks:
  running:
    driver: "bridge"
volumes:
  postgres:
